### ISSUE TITLE
Cursor is not visible when moved on the video area while the volume slider is open

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#461]
Overview Description:

Steps to Reproduce:
1.open celluloid
2.click on the volume icon in the lower right corner
3.while the volume slider is open, move cursor on the video area

Actual Results:
cursor disappears when you hover over the video area
Expected Results:
cursor is always visible while moved
Version:
celluloid-git
Additional Information:
Arch Linux, Gnome 3.32.2 Wayland session

**Comment by MichaelLawton** [comment]
I'm experiencing a similar issue. It seems the fix for the above issue was too small in scope.

Steps to Reproduce:
1. Open celluloid
2. Open any menu or dialog except the volume slider
3. While the menu or dialog is open, move cursor on the video area

Actual Results:
Cursor disappears when you hover over the video area

Expected Results:
Cursor is always visible while moved

Version: 0.19-1~bionic4 from https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv

Additional Information:
Mint 19, Cinnamon 3.8.9 Xorg session

**Comment by MichaelLawton** [comment]
Additionally, sometimes I experience the issue with the volume slider as well. It seems to happen when I first focus on the player controls (e.g. clicking the elapsed/remaining time) and then clicking the volume icon. It works as it should if I first focus on the video before clicking the volume icon.
