### ISSUE TITLE
[Feature Request] Click to toggle play option and adjust arrow key second seek

### ISSUE THREAD

**Issue by tdeeb** [celluloid-player/celluloid#546]
Overview Description:
* Many video players allow clicking on the video to toggle between pausing and resuming the video. Celluloid currently does not feature an option for this.
* Pressing the **left** and **right** arrow keys seeks back and forward, respectively, 5 or 10 seconds depending on its current position - I'm unsure exactly how it determines this. I'd like an option to tell Celluloid exactly how many seconds to seek with the arrow keys.
* Similarly, the **down** and **up** arrow keys seeks back or forward 1 minute, respectively. I'd like to set the seek time, in seconds, for these as well.

Steps to Reproduce:
1. Play a video in Celluloid, ideally 3 minutes or longer.
2. Click on the video.
3. Press the up, down, left, and right arrow keys.

Actual Results:
* When clicking on the video, nothing happens.
* When seeking with the left and right arrow keys, it goes back or forward 5 or 10 seconds.
* When seeking with the down and up arrow keys, it goes back or forward 1 minute.

Expected Results:
* When clicking on the video, the video should toggle between pause and play if the new option is set.
* When seeking with the left and right arrow keys, it goes back or forward as many seconds as specified in the new option.
* When seeking with the down and up arrow keys, it goes back or forward as many seconds as specified in the new option.

Version:
* Celluloid 0.17

Additional Information:
* OS: Linux Mint 19.3 Tina

**Comment by gnome-mpv** [comment]
You can configure all of these using the input config file. It uses the same syntax as mpv's `input.conf`. You can load the file using the `Config Files` tab in preferences.

>Many video players allow clicking on the video to toggle between pausing and resuming the video. Celluloid currently does not feature an option for this.

By default, right clicking the video will do this. If you prefer left click, you can put this in your input config file: `MOUSE_BTN0 cycle pause`

>Pressing the left and right arrow keys seeks back and forward, respectively, 5 or 10 seconds depending on its current position - I'm unsure exactly how it determines this. I'd like an option to tell Celluloid exactly how many seconds to seek with the arrow keys.
>
>Similarly, the down and up arrow keys seeks back or forward 1 minute, respectively. I'd like to set the seek time, in seconds, for these as well.

You can adjust these by putting these options in your input config file:
```
RIGHT seek  5
LEFT  seek -5
UP    seek  60
DOWN  seek -60
```

The numbers are the amount of seconds to seek by. You can change these to your liking.

The inconsistent seeking you see is probably caused by keyframe seeking. This is faster than exact seeking, but can be inaccurate as it can only jump to keyframe boundaries. If you prefer exact seeking, you can add `exact` to the end of each line:
```
RIGHT seek  5 exact
LEFT  seek -5 exact
UP    seek  60 exact
DOWN  seek -60 exact
```

**Comment by tdeeb** [comment]
These all worked perfectly. Thank you so much!
