### ISSUE TITLE
QUESTION noob What is the purposed of the command window that comes up with ` or ~ key?  

### ISSUE THREAD

**Issue by KyleBroflowski** [celluloid-player/celluloid#666]
I'm a noob. Couldnt find related info on the official site or github. What commands can work
 with it? is it same as mpv commands or flags? please clarify
Also I requst to update the man page and provide a detailed description and noob helper on the official website. I realise that this had a lot of hidden features just like mpv

**Comment by gnome-mpv** [comment]
That's the REPL from the mpv-repl plugin. You can use it to run mpv commands (see the `COMMAND INTERFACE` section in mpv's manpage for more details). It used to be a separate plugin, but it's now included with mpv by default.

> Also I requst to update the man page and provide a detailed description and noob helper on the official website.

I don't think it would be appropriate to document it here since it's in mpv, not Celluloid.
