### ISSUE TITLE
How does window size setting work in Celluloid 0.22 ?

### ISSUE THREAD

**Issue by didierga** [celluloid-player/celluloid#719]
Hi,

Apologizes but I don't understand how does window size setting work  in Celluloid 22. I did not have any problem with this from gnome-mpv to celluloid 21.

I already saw tickets https://github.com/celluloid-player/celluloid/issues/713 and https://github.com/celluloid-player/celluloid/issues/705 but it does not help.

I use Fedora 35 under xorg.

Thanks for your help.

**Comment by gnome-mpv** [comment]
Are you trying to stop the window from automatically resizing to fit the video? If so, uncheck the `Automatically resize window to fit video` option in the Preferences dialog (press Ctrl + P to open).

Due to #705, you may need to apply [the patch](https://github.com/celluloid-player/celluloid/commit/52a7d396c846eb337ad7796fdb7163e2bc208d64.patch) or build from git for this to work.

**Comment by didierga** [comment]
Patch was not applied on celluloid-0.22-2.fc35.x86_64

Vasiliy N. Glazov <vascom2@gmail.com> RPMfusion packager just applied it on celluloid-0.22-3.fc35.x86_64 and window size setting work better.

Thanks for your help.

**Comment by gnome-mpv** [comment]
The patched package seems to have been released now, so I think this issue can be closed.
