### ISSUE TITLE
[Question] How do these functions work? (Preferences > Miscellaneous > four items)

### ISSUE THREAD

**Issue by bdh1993** [celluloid-player/celluloid#802]
Overview Description:

![image](https://user-images.githubusercontent.com/58254473/188078076-4a94897a-a48b-498b-8651-2105a0c06d50.png)
![image](https://user-images.githubusercontent.com/58254473/188080691-3d65f73f-bf17-42e5-8b9b-6fcb16b5039f.png)

I want to test the next function.
1. Ignore playback errors
2. Prefetch metadata
3. Enable MPRIS support
4. Enable media keys support

My PC environment is a Linux mint 20.2 or 21 cinnamon environment.
I need to check if this function is what I understand.
I want you to add an image that is easy for me to understand.

**QUESTION**
1. (Ignore playback errors)

- Is the feature an option to ignore when playing broken video files?

2. (Prefetch metadata)

- Where can I use and reproduce this feature?

3. (Enable MPRIS support)

- When checking the function in a cinnamon environment, a playback item was added to the sound-shaped tray icon.
- **Media keys on the keyboard also worked with this option.**

4. (Enable media keys support)

- When the MPRIS function is turned off, the media key does not work.
- **The media key works even if you uncheck media keys support.**

Steps to Reproduce:
1. Start celluloid
2. Open preferences > Miscellaneous
3. check and uncheck functions.

**Comment by gnome-mpv** [comment]
1. Yes. Usually playback errors are shown in a dialog. With that option, errors will just be ignored.
2. This is mostly useful when streaming files over the internet. It makes Celluloid fetch video titles from files in the playlist and display them instead of URLs.
3. This is for enabling the MPRIS protocol support. This is usually used for media keys, but there are other things that use it too, e.g. [playerctl](https://github.com/altdesktop/playerctl).
4. This is for enabling support for Gnome Settings Daemon's Media Keys plugin. You probably don't need it if you are already using MPRIS.
